- name: Générer le fichier Kubernetes depuis Jinja2
  template:
    src: "deployment.yml.j2"
    dest: "{{ k8s_deployment_file }}"

- name: Appliquer le déploiement sur Kubernetes
  command: kubectl apply -f "{{ k8s_deployment_file }}"
  environment:
    KUBECONFIG: "/home/user/.kube/config"
  register: deploy_output
  changed_when: "'configured' in deploy_output.stdout"
  notify: Vérifier le statut du déploiement
