---
- hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster on master
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.10
      register: kubeadm_init
      ignore_errors: yes

    - name: Debug kubeadm init
      debug:
        msg: "{{ kubeadm_init }}"

    - name: Ensure .kube directory exists
      file:
        path: "/home/vagrant/.kube"
        state: directory
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: Copy kubeconfig to user directory on master
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/vagrant/.kube/config"
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: ~/.bashrc
        line: 'export KUBECONFIG=/home/vagrant/.kube/config'
        create: yes

    - name: Apply Flannel CNI network to the cluster
      shell: |
        export KUBECONFIG=/home/vagrant/.kube/config
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      register: flannel_apply

    - name: Debug flannel apply
      debug:
        msg: "{{ flannel_apply }}"

    - name: Exécuter kubeadm pour récupérer la commande de jonction
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Debug join_command
      debug:
        msg: >
          Résultat de la commande :
          stdout: {{ join_command.stdout }}
          stderr: {{ join_command.stderr }}
          rc: {{ join_command.rc }}

    - name: Sauvegarder la commande de jonction pour tous les hôtes
      set_fact:
        join_command_to_workers: "{{ join_command.stdout }}"

    - name: Copier kube/config depuis le master vers la machine locale
      fetch:
        src: "/home/vagrant/.kube/config"
        dest: "/tmp/kube-config"
        flat: yes