apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: "{{ rancher_namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: "{{ rancher_hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher
                port:
                  number: 80
  tls:
    - hosts:
        - "{{ rancher_hostname }}"
      secretName: "{{ cert_name }}"
