# Installer le controlleur Ingress NGINX
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml loadBalancer
- name: Déployer Ingress NGINX
  shell: |
    export KUBECONFIG=/home/vagrant/.kube/config
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml
  args:
    executable: /bin/bash

- name: Attendre que le contrôleur Ingress soit opérationnel
  shell: |
    export KUBECONFIG=/home/vagrant/.kube/config
    kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
  args:
    executable: /bin/bash


