- name: Initialize Kubernetes cluster on master
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.10
  register: kubeadm_init
  ignore_errors: yes

- name: Debug kubeadm init
  debug:
    msg: "{{ kubeadm_init }}"

- name: Ensure .kube directory exists
  file:
    path: "/home/vagrant/.kube"
    state: directory
    mode: '0755'
    owner: vagrant
    group: vagrant

- name: Copy kubeconfig to user directory on master
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/vagrant/.kube/config"
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: ~/.bashrc
    line: 'export KUBECONFIG=/home/vagrant/.kube/config'
    create: yes

- name: Generate Kubernetes join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Save join command for workers
  set_fact:
    join_command_to_workers: "{{ join_command.stdout }}"

- name: Fetch kubeconfig file to local machine
  fetch:
    src: "/home/vagrant/.kube/config"
    dest: "/tmp/kube-config"
    flat: yes

#sudo apt update
#sudo apt install python3-pip
#sudo pip3 install kubernetes

