all:
  hosts:
    master:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
    worker1:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
    worker2:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
  children:
    k8s_cluster:
      hosts:
        master:
        worker1:
        worker2:

