---
- name: Cloner le projet sur la machine contrôleur Ansible
  hosts: localhost
  gather_facts: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yaml
    - vars/docker_secrets.yaml

  roles:
    - clone_repo
    # - run_test
    - build_docker 
